spring:
  application:
    name: eureka-client-service

server:
  port: 9901

eureka:
  instance:
    hostname: micro-app-eureka-client.herokuapp.com
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: https://micro-app-eureka.herokuapp.com/eureka